---
  - name: "Claim an OCP cluster from pool"
    hosts: hive_instance
    gather_facts: yes
    vars_files:
      pool-vars.yml
    vars:
      kubeadmin_password: "{{ hive_hub_password }}"

    environment:
      PATH: ".:{{ ansible_env.PATH }}"

    roles:
      - oc_client_install
      - ocp_login # login to hive cluster
      - ocp_pool_claim

  - name: "setup claimed ocp cluster"
    hosts: ocp_claimed_cluster
    vars_files:
      custom-vars.yml

    environment:
      PATH: ".:{{ ansible_env.PATH }}"

    roles:
      - role: ocp_login # claimed cluster login
        when: admin_task == "claim"

      - role: request_ocs
        when: ocs_storage == "true" and admin_task == "claim"

      - role: request_ocp4_logging
        when: ocp_logging == "true" and admin_task == "claim"

      - role: clone_repo
        when: post_install == "true" and admin_task == "claim"

      - role: "{{ post_install_role }}"
        when: post_install == "true" and admin_task == "claim"        
      
      - role: ocp_cluster_tag
        vars:
          CLUSTER_NAME: "{{ cluster_name }}"
        when: admin_task == "claim"

    tasks:

      - name: Display cluster details
        command: "cat {{ claim_name }}_details.log"
        register: cluster_details

      - name: Print details
        debug:
          msg: "{{ cluster_details.stdout }}"
